spring:
  application:
    name: ADMIN-SERVICE
  profile:
    active: dev
  cloud:
    config:
      name: admin-service
      uri: http://configuration-server:8888
      import: "optional:configserver:"
